title: Tekoa
description: BBB's Tekoa is an AI interface that helps government's agency!
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
site.github.zip_url: https://demo.bbb.bot
site.github.tar_url: https://bbb.bot